#!/bin/sh
# Lot GLM DÉCOUPÉ (parade panne 1 « length » + reprise sur erreur serveur) — un seul jalon par lot, 3 passes courtes.
# Usage : lot_glm_decoupe.sh <lot> <ID> <produit: job|twitter|tiktok|usine> <fichier COMMUN modèle> <fichier consigne spécifique> [temoin]
B="$(cd "$(dirname "$0")" && pwd)"; R="$B/../.."; N="$B/$1"; ID="$2"; P="$3"; mkdir -p "$N"; : >> "$N/FILE.log"; cd "$B"
sed "s#NOUVEAUX_[A-Za-z0-9_]*/#$1/#g; s#écris SEULEMENT dans \.context/RADAR/NOUVEAUX_[A-Za-z0-9_]*#écris SEULEMENT dans .context/RADAR/$1#g" "$4" > "$N/COMMUN.txt"; echo "CODE DE RÉFÉRENCE (le SEUL qui compte) : .context/RADAR/$P/copie à HEAD — l'acceptation rejoue tes blocs « ancien » sur CETTE version : recopie-les à l'octet depuis SES fichiers, jamais depuis une autre copie ; chemins relatifs à SA racine, dans « livrables »." >> "$N/COMMUN.txt"  # 30/09 : cause n°1 des refus = GLM lisait une autre version
R1="MINIMUM de code et de complexité, simple et rock solide : prends un outil établi ou retire une ligne avant d'en ajouter. écris chaque fichier IMMÉDIATEMENT avec l'outil d'écriture, un fichier à la fois, ≤ 120 lignes ; ne rédige AUCUNE réponse longue ; ne mets jamais plusieurs fichiers dans une seule réponse."
{ echo "PASSE 1 — JALON IMPOSÉ $ID."; cat "$5"; echo "Écris $1/CANDIDATS.md (≤ 30 lignes : but, épreuves, ce qui est ROUGE à la base, 2 triches), PUIS $1/$ID/contrat.yaml. RÈGLE (29/09) : le champ tache dit EN CLAIR, une ligne par point, CHAQUE chose que le juge vérifiera (sans montrer le code du juge) ; un jalon touche 1 à 2 fichiers au plus — sinon découpe et dis-le dans CANDIDATS.md. Puis $1/_DONE_1.txt. $R1"; } > "$N/P1.txt"  # 01/10 levier 2 (croisement 3 IA) : 5 passes → 3
echo "PASSE 2 — $ID : relis $1/$ID/contrat.yaml. Écris SEULEMENT $1/$ID/test_$(echo $ID | tr 'A-Z' 'a-z').py (le juge) : il ne vérifie RIEN qui ne soit écrit dans le champ tache du contrat. Puis $1/_DONE_2.txt. $R1" > "$N/P2.txt"
echo "PASSE 3 — $ID : écris $1/$ID/honnete.patch.md (blocs « ancien » copiés À L'OCTET du fichier actuel ; relis chaque assertion du juge), PUIS $1/$ID/triche1.patch.md, PUIS $1/$ID/triche2.patch.md : chaque triche s'applique au code ACTUEL (la base, PAS la correction honnête), blocs « ancien » copiés À L'OCTET de la base, et doit faire ÉCHOUER au moins une assertion du juge. Puis $1/_DONE_3.txt. $R1" > "$N/P3.txt"
NP=3; if [ "$6" = temoin ]; then NP=4; echo "PASSE 4 — $ID : écris SEULEMENT $1/CONTROLE/test_controle_$(echo $ID | tr 'A-Z' 'a-z').py : SUITE DE CONTRÔLE plus stricte que le juge (cas limites), jamais montrée aux constructeurs. Puis $1/_DONE_4.txt. $R1" > "$N/P4.txt"; fi
for essai in 1 2; do D=1; while [ -f "$N/_DONE_$D.txt" ]; do D=$((D+1)); done; [ "$D" -gt "$NP" ] && break
  for f in "$N"/glm_p*.jsonl; do [ -f "$f" ] && mv "$f" "$f.essai$essai.$(date +%s)"; done
  DEBUT=$D sh "$R/.context/CLOTURE_20260927/glm_restreint.sh" "$R" ".context/RADAR/$1" $NP && break; echo "$(date +%T) reprise à la passe manquante (essai $essai)" >> "$N/FILE.log"; done
[ -f "$N/$ID/contrat.yaml" ] || { echo "$(date +%T) ARRÊT : pas de contrat" >> "$N/FILE.log"; exit 1; }
[ "$6" = temoin ] && exit 0
timeout 3000 python3 accepter_jalon.py "$P/projet" "$P/copie" "$N/$ID" > "$N/$ID/acceptation.out" 2>&1
echo "$(date +%T) acceptation : $(grep -E 'ACCEPTÉ|REFUS' "$N/$ID/acceptation.out" | tail -1 | cut -c1-200)" >> "$N/FILE.log"
grep -q "REFUS" "$N/$ID/acceptation.out" && [ ! -d "$N/passes_initiales" ] && sh "$B/corriger_lot_glm.sh" "$1" "$ID" "$P"  # 30/09 : un refus lance SA correction (1 fois)
grep -q "ACCEPTÉ" "$N/$ID/acceptation.out" || exit 1; [ -f "$B/$P/ARRET" ] || pgrep -f "^sh .*chaine_mf\.sh .* $P$" >/dev/null || { R=$(cd "$R" && pwd); python3 "$R/.context/BUILD_V3_2026-09-25/detache.py" "$B/chaine_$P.out" sh -c "env -u FACTORY_NO_REAL_ENGINE sh '$B/chaine_mf.sh' '$R' '$P'; [ '$P' = usine ] || timeout 1500 python3 '$B/integrer.py' '$P'" >/dev/null; }; exit 0  # 01/10 : accepté = rc 0 (sinon relancé 3× : gaspillage mesuré DN0GZ/DN0FZ/DN1A) et construit TOUT DE SUITE
